import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '../components/header'
import { CartContextProvider } from '@/context/cart'
import Footer from '@/components/footer'
import { CookiesProvider } from 'next-client-cookies/server'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <CartContextProvider>
          <CookiesProvider>
            <Header />
            <div className="min-h-screen">{children}</div>
            <Footer />
          </CookiesProvider>
        </CartContextProvider>
      </body>
    </html>
  )
}
